- name: Download
  get_url:
    url: https://github.com/tkuchiki/alp/releases/download/v1.0.21/alp_linux_amd64.tar.gz
    dest: /tmp/

- name: Unarchive
  unarchive:
    src: /tmp/alp_linux_amd64.tar.gz
    dest: /tmp/
    remote_src: true
  ignore_errors: true

- name: install
  shell: sudo install /tmp/alp /usr/local/bin

- name: remove file
  file:
    path: /tmp/alp
    state: absent

- name: remove file
  file:
    path: /tmp/alp_linux_amd64.tar.gz
    state: absent
