name: "pt-query-digest"
on:
  workflow_dispatch:
jobs:
  Mysql:
    name: "Mysql Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Exe pt-query-digest
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.MYSQL }}
          username: isucon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo sed -i '/^INSERT INTO `posts`/d' /var/log/mysql/mysql-slow.log
            sudo pt-query-digest /var/log/mysql/mysql-slow.log
