- name: Download
  get_url:
    url: https://github.com/tkuchiki/slp/releases/download/v0.2.0/slp_linux_amd64.tar.gz
    dest: /tmp/

- name: Unarchive
  unarchive:
    src: /tmp/slp_linux_amd64.tar.gz
    dest: /tmp/
    remote_src: true
  ignore_errors: true

- name: install
  shell: sudo install /tmp/slp /usr/local/bin

- name: remove file
  file:
    path: /tmp/slp
    state: absent

- name: remove file
  file:
    path: /tmp/slp_linux_amd64.tar.gz
    state: absent
