var:
  all:
    isu:
      - isu/isu_deploy.yml
      - isu/isu_challenge.yml
    tools:
      - tools/common.yml
      - tools/nginx.yml
      - tools/mysql.yml
      - tools/netdata.yml
      - tools/alp.yml
      - tools/slp.yml
      - tools/pprotein-agent.yml
      - tools/sysctl.yml
  isu1:
    isu:
    tools:
      - tools/collect.yml
      - tools/fetch.yml
      - tools/graphviz.yml
  isu2:
    isu:
    tools:
  isu3:
    isu:
    tools:
