var:
  isu1:
    tasks:
      - isu/isu_deploy.yml
    tools:
      - tools/common.yml
      - tools/collect.yml
      - tools/fetch.yml
      - tools/graphviz.yml
      - tools/nginx.yml
      - tools/mysql.yml
      - tools/netdata.yml
      - tools/slp.yml
      - tools/pprotein-agent.yml
      - tools/sysctl.yml

      # ------------------------------
      # - tools/alp.yml
      # - tools/redis.yml

  isu2:
    tasks:
    tools:
  isu3:
    tasks:
    tools:
