name: "Bench Measure"
on:
  workflow_dispatch:

jobs:
  Pprof:
    name: "Pprof Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Exe
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST1 }}
          username: isucon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sleep 7
            # sudo curl -o /tmp/cpu.pprof http://localhost:6060/debug/pprof/profile?seconds=60
            curl -o /tmp/cpu_$$(date +"%Y-%m-%d-%H-%M-%S").pprof http://localhost:6060/debug/fgprof?seconds=60

  Bench:
    name: "Bench Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Exe
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST_BENCH }}
          username: isucon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo -u isucon /home/isucon/private_isu.git/benchmarker/bin/benchmarker -u /home/isucon/private_isu.git/benchmarker/userdata -t http://${{ vars.HOST1 }}

  Measure:
    name: "Measure Job"
    needs: Bench
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Exe alp
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST1 }}
          username: isucon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo cat /var/log/nginx/access.log \
            | alp ltsv -m '/image/[0-9]+,/posts/[0-9]+,/@\w' \
            --sort avg -r -o count,1xx,2xx,3xx,4xx,5xx,min,max,avg,sum,p99,method,uri

      - name: Exe pt-query-digest
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST1 }}
          username: isucon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo sed -i '/^INSERT INTO `posts`/d' /var/log/mysql/mysql-slow.log
            sudo pt-query-digest /var/log/mysql/mysql-slow.log
