- name: shell
  become: true
  shell: |
    mysql -u isuconp -pisuconp isuconp -e "alter table comments add index post_id_index (post_id, created_at DESC);"
    mysql -u isuconp -pisuconp isuconp -e "alter table posts add index posts_order_idx (created_at DESC);"
    mysql -u isuconp -pisuconp isuconp -e "alter table posts add index posts_user_idx (user_id, created_at DESC);"
  ignore_errors: true

- name: Copy
  become: true
  copy:
    src: ../../files/nginx/sites-available/isucon.conf
    dest: /etc/nginx/sites-available/isucon.conf
    mode: "0644"
    backup: true

- name: nginx is restarted
  become: true
  systemd:
    name: nginx
    state: restarted

- name: mysql is restarted
  become: true
  systemd:
    name: mysql
    state: restarted
