name: "pprof"
on:
  workflow_dispatch:
jobs:
  Pprof:
    name: "Pprof Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Exe
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.PPROF }}
          username: isucon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sleep 7
            # sudo curl -o /tmp/cpu.pprof http://localhost:6060/debug/pprof/profile?seconds=60
            curl -o /tmp/cpu_$$(date +"%Y-%m-%d-%H-%M-%S").pprof http://localhost:6060/debug/fgprof?seconds=60
